Política 1

Cualquier ejecución de streaming de video en oficina será denegada por el sistema.

rule "policy-1 FLV"
when
	squid:Squid(dif_MCT=="video",dif_content matches "*.video.*")
then
	PolicyDecisionPoint.deny();
end

rule "policy-1 MP4"
when
	squid:Squid(dif_MCT=="video",bytes>1000000, content_type matches "*.application.*, url matches "*.p2p.* )
then
	PolicyDecisionPoint.deny();
end


Política 2

Cualquier descarga de videos en oficina será denegada por el sistema.

rule "policy-2 Download"
when
	squid:Squid(http_method=="PUT", bytes>1000000)
then
	PolicyDecisionPoint.deny();
end

rule "policy-4 Allowed put"
when
	squid:Squid(http_method=="PUT", bytes<1000000)
then
	PolicyDecisionPoint.allow();
end

Política 3

La utilización de aplicaciones de la blacklist será denegada por la organización.

rule "policy-3 Blacklist Dropbox"
when
	squid:Squid(url matches "*.dropbox.*", diff_content matches "*.application.*")
then
	PolicyDecisionPoint.deny();
end

rule "policy-3 Blacklist Logmein"
when
	squid:Squid(url matches "*.logmein.*", diff_content matches "*.application.*")
then
	PolicyDecisionPoint.deny();
end

rule "policy-3 Blacklist Gmail"
when
	squid:Squid(url matches "*.gmail.*", diff_content matches "*.application.*")
then
	PolicyDecisionPoint.deny();
end

rule "policy-3 Blacklist Google Drive"
when
	squid:Squid(url matches "*.googledrive.*", diff_content matches "*.application.*")
then
	PolicyDecisionPoint.deny();
end

rule "policy-3 Exception Youtube"
when
	squid:Squid(url matches "*.youtube.*", diff_content matches "*.application.*")
then
	PolicyDecisionPoint.deny();
end

